services:

  tests:
    image: assemblage-gcc:default
    build:
      context: .
      dockerfile: docker/gcc/Dockerfile
    ## run all tests except the one in assemblage/windows/parsers:
    command: python -m unittest discover -s test -p '*_test.py'
    ## run one test:
    #command: python /app/test/unit_tests/workers/coordinator_test.py 
    environment: # do not remove!!
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      PYTHONUNBUFFERED: 1
      TYPE: tests
      name: tests
    env_file:
      - secrets.env
    volumes:
      - ./backend:/app 