services:

  win_builder:
    image: assemblage-windows:latest
    build:
      context: .
      dockerfile: docker/windows/Dockerfile
    command: python3 /app/scripts/workers/example_cluster.py --type builder --id 0
    healthcheck:
      test: [ "CMD", "bash", "-c", "pgrep -f example_cluster.py > /dev/null" ]
      interval: 10s
      start_period: 5s
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      name: win_builder
    env_file:
      - secrets.env
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./backend:/app 
      - builder-data:/binaries
    mem_limit: 250g

volumes:
  builder-data:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: ${PWD}/binaries

