services:
# see the readme in assemblage/test for instructions on setting up integration tests
  test-database:
    container_name: assemblage-test-db
    image: postgres:18.0-alpine3.22
    env_file:
      - secrets.env
    environment:
      - POSTGRES_USER=assemblage # do not change!
    volumes:
      - test-database-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "assemblage"]
      interval: 2s
      timeout: 1s
      retries: 10
  tests:
    image: assemblage-gcc:default
    build:
      context: .
      dockerfile: docker/gcc/Dockerfile

    ## setup command (run before first time testing, or whenever you delete the db)
    #entrypoint: ['python', '/app/test/integration_tests/setup.py']
    ## run all integration tests:
    entrypoint: ['python', '-m', 'unittest', 'discover', '-s', 'test/integration_tests', '-p', '*_test.py']
    ## run one test:
    #entrypoint: ['python', '/app/test/integration_tests/db_manager_test.py', 'TestDBManager.test_get_projects_row_by_id']
    environment: # do not remove!!
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      PYTHONUNBUFFERED: 1
      TYPE: tests
      name: tests
    env_file:
      - secrets.env
    volumes:
      - ./backend:/app 
    depends_on:
      test-database:
        condition: service_healthy


        
volumes:
  test-database-data:
    driver: local