services:

  database:
    container_name: assemblage-db
    image: mysql:8.0.32
    env_file:
      - secrets.env
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit consumer_timeout 900000
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    # ports:
    # - '56723'
    # - 5672:5672
  coordinator:
    image: assemblage-gcc:default
    build:
      context: .
      dockerfile: docker/gcc/Dockerfile
    command: python3 /app/scripts/workers/example_cluster.py --type  coordinator
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    env_file:
      - secrets.env
    healthcheck:
      test: [ "CMD", "bash", "-c", "pgrep -f example_cluster.py > /dev/null && test -f /tmp/setup_complete.txt" ]
      interval: 10s
      start_period: 5s
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - shared-data:/binaries
      - ./backend:/app 
  scraper_0:
    image: assemblage-gcc:default
    build:
      context: .
      dockerfile: docker/gcc/Dockerfile
    command: python3 /app/scripts/workers/example_cluster.py --type scraper --id 0
    depends_on:
      coordinator:
        condition: service_healthy
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    env_file:
      - secrets.env
    deploy:
      resources:
        limits:
          memory: 2048M
      restart_policy:
        condition: on-failure
    volumes:
      - shared-data:/binaries
      - ./backend:/app 
  builder_0:
    image: assemblage-clang:default
    build:
      context: .
      dockerfile: docker/clang/Dockerfile
    command: python3 /app/scripts/workers/example_cluster.py --type builder --id 0
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    env_file:
      - secrets.env
    depends_on:
      coordinator: 
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - shared-data:/binaries
      - ./backend:/app 


# web server
  web-backend:
    image: assemblage-web-backend:latest
    command: uvicorn scripts.web_server:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app
    build:
      context: .
      dockerfile: docker/web/backend/Dockerfile
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
        - secrets.env
    volumes:
        - ./backend:/app 
    ports:
       - 8000:8000

  web-frontend: 
    image: assemblage-web-frontend:latest
    depends_on:
      - web-backend
    build: 
      context: .
      dockerfile: docker/web/frontend/Dockerfile.dev
    volumes: 
        - ./frontend:/app
        - /app/node_modules # prevents then from being overwritten by not existing locally!
    ports:
      - "80:3000"

volumes:
  shared-data:
    driver: local
    driver_opts:
      device: ${PWD}/binaries
      o: bind
      type: none
  db-data:
    driver: local
