services:

  database: 
    container_name: assemblage-db
    image: mysql:8.0.32
    env_file:
      - secrets.env
    volumes: 
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  builder_0:
    command: python3 /assemblage/example_cluster.py --type builder --id 0
    environment: 
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    env_file:
      - secrets.env
    depends_on:
      coordinator:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
    image: clang
    volumes:
    - ./binaries:/binaries
    - .:/assemblage

  coordinator:
    image: assemblage-gcc:default
    command: python3  /assemblage/example_cluster.py --type  coordinator
    environment: 
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    env_file:
      - secrets.env
    healthcheck:
      test: ["CMD", "bash", "-c", "pgrep -f example_cluster.py > /dev/null && test -f /tmp/setup_complete.txt"]
      interval: 10s
      start_period: 5s
    depends_on:
      database:
        condition: service_healthy
      rabbitmq: 
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
    ports:
    - 50052:50052
    volumes:
    - shared-data:/binaries
    - .:/assemblage

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit consumer_timeout 900000
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    # ports:
    # - '56723'
    # - 5672:5672
  scraper_0:
    command: python3  /assemblage/example_cluster.py --type  scraper  --id 0
    depends_on:
      coordinator:
        condition: service_healthy
    environment: 
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    env_file:
      - secrets.env
    deploy:
      resources:
        limits:
          memory: 2048M
      restart_policy:
        condition: on-failure
    image: assemblage-gcc:default
    volumes:
    - shared-data:/binaries
    - .:/assemblage

volumes:
  shared-data:
    driver: local
    driver_opts:
      device: ${PWD}/binaries
      o: bind
      type: none
  db-data:
    driver: local

